using Assets.Scripts.Gameplay.Player;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
{
    private HealthSystem healthSystem;
    [SerializeField] private PlayerMovement playerMovement;
    [SerializeField] private SpriteRenderer spriteRenderer;
    [Header("VFX")]
    [SerializeField] private GameObject jumpSplash;
    [Header("Sound clips")]
    [SerializeField] private AudioClip clipHurt;
    [SerializeField] private AudioClip clipDie;

    private Animator animator;
    private List<State> states = new();
    [SerializeField] private State currentState;
    [SerializeField] private State previousState;

    private void Awake()
    {
        healthSystem = GetComponent<HealthSystem>();
        animator = GetComponent<Animator>();
        playerMovement.OnJump += PlayerMovement_onJump;
        healthSystem.OnDie += HealthSystem_onDie;
        healthSystem.OnLifeUpdated += HealthSystem_onLifeUpdated;
        healthSystem.OnHealing += HealthSystem_onHealing;
    }

    private void Start()
    {
        states.Add(new StateIdle(playerMovement, this));
        states.Add(new StateWalk(playerMovement, this));
        states.Add(new StateJump(playerMovement, this));

        SwapStateTo(PlayerAnimatorEnum.Idle);
    }

    private void Update()
    {
        currentState.Update();
    }

    private void OnDestroy()
    {
        playerMovement.OnJump -= PlayerMovement_onJump;
        healthSystem.OnDie -= HealthSystem_onDie;
        healthSystem.OnLifeUpdated -= HealthSystem_onLifeUpdated;
        healthSystem.OnHealing -= HealthSystem_onHealing;
    }

    private void PlayerMovement_onJump(bool jump)
    {
        spriteRenderer.enabled = !jump;
        jumpSplash.SetActive(jump);
    }

    private void HealthSystem_onLifeUpdated(int life, int maxLife, bool takeDmgMyselft)
    {
        if (life < maxLife && !takeDmgMyselft)
        {
            CombatEvents.RaiseCameraShake(2f, 0.12f, transform.position);
            AudioController.Instance.PlaySoundEffect(clipHurt, priority: 2);
        }
    }

    private void HealthSystem_onHealing(int life, int maxLife, bool takeDmgMyselft)
    {
    }

    private void HealthSystem_onDie()
    {
        AudioController.Instance.PlaySoundEffect(clipDie, priority: 3);
        GameStateManager.Instance.SetGameState(GameState.GAME_OVER);
    }

    public void SwapStateTo(PlayerAnimatorEnum nextState)
    {
        foreach (State state in states)
        {
            if (state.state == nextState)
            {
                currentState?.OnExit();

                currentState = state;
                currentState.OnEnter();
                break;
            }
        }
    }

    public void ChangeAnimatorState(int state)
    {
        animator.SetInteger("State", state);
    }
}